// js/products.js - 唯一产品数据源
// 价格来自产品信息采集表1.xlsx, tiers 保留但不渲染
// 图片文件名已全小写

window.PRODUCTS = [
  {
    id: "I74-915",
    cat: "living",
    name: "Napa Rec. Sofa Table",
    nameZh: "纳帕沙发桌",
    desc: "Solid wood frame, camphor veneer & other man-made wood accessories. Eco-friendly water-based paint. Shipped as-is in original export boxes.",
    descZh: "实木框架，樟木皮及其他人造木配件，环保水性漆，原出口包装出货。",
    price: 159,
    oldPrice: 959,
    stock: 16,
    dimensions: "W137×D46×H78 cm",
    weight: "75 kg",
    packaging: "0.29 CBM",
    material: "Solid wood frame, camphor veneer & other man-made wood accessories",
    materialZh: "实木框架 + 樟木皮 + 人造木配件",
    finish: "Eco-friendly water-based paint",
    finishZh: "环保水性漆",
    flaw: "Overstock clearance. Shipped as-is. Discount covers box wear, dust and possible unknown product faults.",
    flawZh: "清仓库存，按现状出货。折扣已涵盖包装磨损、积尘及可能的未知瑕疵。",
    images: ["img/i74-915-1.jpg","img/i74-915-2.jpg","img/i74-915-3.jpg","img/i74-915-4.jpg","img/i74-915-5.jpg","img/i74-915-6.jpg","img/i74-915-7.jpg","img/i74-915-8.jpg","img/i74-915-9.jpg"],
    video: "img/i74-915.mp4",
    tiers: { "1-9": 159, "10-19": 145, "20+": 135 },
    featured: true
  },
  {
    id: "I74-910",
    cat: "living",
    name: "Napa Cocktail Table",
    nameZh: "纳帕咖啡桌",
    desc: "Solid wood frame, camphor veneer & other man-made wood accessories. Eco-friendly water-based paint. Shipped as-is in original export boxes.",
    descZh: "实木框架，樟木皮及其他人造木配件，环保水性漆，原出口包装出货。",
    price: 179,
    oldPrice: 1199,
    stock: 3,
    dimensions: "W127×D82×H51 cm",
    weight: "63 kg",
    packaging: "0.46 CBM",
    material: "Solid wood frame, camphor veneer & other man-made wood accessories",
    materialZh: "实木框架 + 樟木皮 + 人造木配件",
    finish: "Eco-friendly water-based paint",
    finishZh: "环保水性漆",
    flaw: "Overstock clearance. Shipped as-is. Discount covers box wear, dust and possible unknown product faults.",
    flawZh: "清仓库存，按现状出货。折扣已涵盖包装磨损、积尘及可能的未知瑕疵。",
    images: ["img/i74-910-1.jpg","img/i74-910-2.jpg","img/i74-910-3.jpg","img/i74-910-4.jpg","img/i74-910-5.jpg","img/i74-910-6.jpg","img/i74-910-7.jpg","img/i74-910-8.jpg","img/i74-910-9.jpg"],
    video: "img/i74-910.mp4",
    tiers: { "1-9": 179, "10-19": 165, "20+": 149 },
    featured: true
  },
  {
    id: "I77-364WD",
    cat: "study",
    name: "64\" Writing Desk",
    nameZh: "64英寸写字台",
    desc: "Solid wood frame, Dalbergia veneer & other engineered wood components. Eco-friendly water-based paint. Shipped as-is in original export boxes.",
    descZh: "实木框架，黄檀木皮及其他工程木组件，环保水性漆，原出口包装出货。",
    price: 179,
    oldPrice: 1199,
    stock: 17,
    dimensions: "W163×D61×H78 cm",
    weight: "57 kg",
    packaging: "0.34 CBM",
    material: "Solid wood frame, Dalbergia veneer & other engineered wood components",
    materialZh: "实木框架 + 黄檀木皮 + 工程木组件",
    finish: "Eco-friendly water-based paint",
    finishZh: "环保水性漆",
    flaw: "Overstock clearance. Shipped as-is. Discount covers box wear, dust and possible unknown product faults.",
    flawZh: "清仓库存，按现状出货。折扣已涵盖包装磨损、积尘及可能的未知瑕疵。",
    images: ["img/i77-364wd-1.jpg","img/i77-364wd-2.jpg","img/i77-364wd-3.jpg","img/i77-364wd-4.jpg","img/i77-364wd-5.jpg","img/i77-364wd-6.jpg"],
    video: "img/i77-364wd.mp4",
    tiers: { "1-9": 179, "10-19": 165, "20+": 149 },
    featured: true
  },
  {
    id: "I77-455",
    cat: "bedroom",
    name: "Chesser",
    nameZh: "带镜斗柜",
    desc: "Solid wood frame, Dalbergia veneer & other engineered wood components. Eco-friendly water-based paint. Shipped as-is in original export boxes.",
    descZh: "实木框架，黄檀木皮及其他工程木组件，环保水性漆，原出口包装出货。",
    price: 199,
    oldPrice: 1299,
    stock: 4,
    dimensions: "W155×D55×H128 cm",
    weight: "130 kg",
    packaging: "1.22 CBM",
    material: "Solid wood frame, Dalbergia veneer & other engineered wood components",
    materialZh: "实木框架 + 黄檀木皮 + 工程木组件",
    finish: "Eco-friendly water-based paint",
    finishZh: "环保水性漆",
    flaw: "Overstock clearance. Shipped as-is. Discount covers box wear, dust and possible unknown product faults.",
    flawZh: "清仓库存，按现状出货。折扣已涵盖包装磨损、积尘及可能的未知瑕疵。",
    images: ["img/i77-455-1.jpg","img/i77-455-2.jpg","img/i77-455-3.jpg","img/i77-455-4.jpg","img/i77-455-5.jpg","img/i77-455-6.jpg","img/i77-455-7.jpg","img/i77-455-8.jpg"],
    video: "img/i77-455.mp4",
    tiers: { "1-9": 199, "10-19": 185, "20+": 169 },
    featured: true
  },
  {
    id: "I77-456",
    cat: "bedroom",
    name: "Gentleman's Chest w/storage",
    nameZh: "绅士储物高柜",
    desc: "Solid wood frame, Dalbergia veneer & other engineered wood components. Eco-friendly water-based paint. Shipped as-is in original export boxes.",
    descZh: "实木框架，黄檀木皮及其他工程木组件，环保水性漆，原出口包装出货。",
    price: 199,
    oldPrice: 1299,
    stock: 6,
    dimensions: "W96×D54×H135 cm",
    weight: "110 kg",
    packaging: "1.10 CBM",
    material: "Solid wood frame, Dalbergia veneer & other engineered wood components",
    materialZh: "实木框架 + 黄檀木皮 + 工程木组件",
    finish: "Eco-friendly water-based paint",
    finishZh: "环保水性漆",
    flaw: "Overstock clearance. Shipped as-is. Discount covers box wear, dust and possible unknown product faults.",
    flawZh: "清仓库存，按现状出货。折扣已涵盖包装磨损、积尘及可能的未知瑕疵。",
    images: ["img/i77-456-1.jpg","img/i77-456-2.jpg","img/i77-456-3.jpg","img/i77-456-4.jpg","img/i77-456-5.jpg","img/i77-456-6.jpg","img/i77-456-7.jpg","img/i77-456-8.jpg"],
    video: "img/i77-456.mp4",
    tiers: { "1-9": 199, "10-19": 185, "20+": 169 },
    featured: true
  },
  {
    id: "I77-485",
    cat: "living",
    name: "Entertainment Chest",
    nameZh: "电视柜",
    desc: "Solid wood frame, Dalbergia veneer & other engineered wood components. Eco-friendly water-based paint. Shipped as-is in original export boxes.",
    descZh: "实木框架，黄檀木皮及其他工程木组件，环保水性漆，原出口包装出货。",
    price: 199,
    oldPrice: 1299,
    stock: 6,
    dimensions: "W120×D55×H97 cm",
    weight: "86 kg",
    packaging: "0.87 CBM",
    material: "Solid wood frame, Dalbergia veneer & other engineered wood components",
    materialZh: "实木框架 + 黄檀木皮 + 工程木组件",
    finish: "Eco-friendly water-based paint",
    finishZh: "环保水性漆",
    flaw: "Overstock clearance. Shipped as-is. Discount covers box wear, dust and possible unknown product faults.",
    flawZh: "清仓库存，按现状出货。折扣已涵盖包装磨损、积尘及可能的未知瑕疵。",
    images: ["img/i77-485-1.jpg","img/i77-485-2.jpg","img/i77-485-3.jpg","img/i77-485-4.jpg","img/i77-485-5.jpg","img/i77-485-6.jpg","img/i77-485-7.jpg","img/i77-485-8.jpg","img/i77-485-9.jpg"],
    video: "img/i77-485.mp4",
    tiers: { "1-9": 199, "10-19": 185, "20+": 169 },
    featured: true
  },
  {
    id: "I77-6030",
    cat: "dining",
    name: "Trestle Table Base & Top",
    nameZh: "伸缩餐桌",
    desc: "Solid wood frame, Dalbergia veneer & other engineered wood components. Eco-friendly water-based paint. Extendable design. Shipped as-is in original export boxes.",
    descZh: "实木框架，黄檀木皮及其他工程木组件，环保水性漆，可伸缩设计，原出口包装出货。",
    price: 299,
    oldPrice: 1799,
    stock: 5,
    dimensions: "W198×D112×H80 cm / W290×D112×H80 cm (extended)",
    weight: "118 kg",
    packaging: "0.89 CBM",
    material: "Solid wood frame, Dalbergia veneer & other engineered wood components",
    materialZh: "实木框架 + 黄檀木皮 + 工程木组件",
    finish: "Eco-friendly water-based paint",
    finishZh: "环保水性漆",
    flaw: "Overstock clearance. Shipped as-is. Discount covers box wear, dust and possible unknown product faults.",
    flawZh: "清仓库存，按现状出货。折扣已涵盖包装磨损、积尘及可能的未知瑕疵。",
    images: ["img/i77-6030-1.jpg","img/i77-6030-2.jpg","img/i77-6030-3.jpg","img/i77-6030-4.jpg","img/i77-6030-5.jpg","img/i77-6030-6.jpg","img/i77-6030-7.jpg","img/i77-6030-8.jpg","img/i77-6030-9.jpg"],
    video: "img/i77-6030bt.mp4",
    tiers: { "1-9": 299, "10-19": 279, "20+": 259 },
    featured: true
  }
];